function cellInfo = Controls_Bus_Creator(varargin) 
% STATES_BUS_CREATOR returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'Controls_bus_T', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'d_e', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('m'), ''}; ...
{'d_th', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('m'), ''}; ...
{'d_a', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('m'), ''}; ...
{'d_r', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('rad'), ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
