function cellInfo = States_Bus_Creator(varargin) 
% STATES_BUS_CREATOR returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'Initial_States_bus_T', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'x', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('ft'), ''}; ...
{'y', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('ft'), ''}; ...
{'z', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('ft'), ''}; ...
{'u', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('ft/s'), ''}; ...
{'v', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('ft/s'), ''}; ...
{'w', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('ft/s'), ''}; ...
{'p', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('rad/s'), ''}; ...
{'q', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('rad/s'), ''}; ...
{'r', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('rad/s'), ''}; ...
{'phi', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('rad'), ''}; ...
{'theta', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('rad'), ''}; ...
{'psi', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('rad'), ''}; ...
{'alpha', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('rad'), ''}; ...
{'beta', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('rad'), ''}; ...
{'wdot', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('rad/s/s'), ''}; ...
    } ...
  } ...
  { ... 
    'Controls_bus_T', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'d_e', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('rad'), ''}; ...
{'d_th', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('N'), ''}; ...
{'d_a', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('rad'), ''}; ...
{'d_r', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('rad'), ''}; ...
    } ...
  } ...
  { ... 
    'States_bus_T', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'x', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('ft'), ''}; ...
{'y', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('ft'), ''}; ...
{'z', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('ft'), ''}; ...
{'u', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('ft/s'), ''}; ...
{'v', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('ft/s'), ''}; ...
{'w', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('ft/s'), ''}; ...
{'p', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('rad/s'), ''}; ...
{'q', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('rad/s'), ''}; ...
{'r', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('rad/s'), ''}; ...
{'phi', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('rad'), ''}; ...
{'theta', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('rad'), ''}; ...
{'psi', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('rad'), ''}; ...
{'alpha', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('rad'), ''}; ...
{'beta', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('rad'), ''}; ...
{'VT', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('ft/s'), ''}; ...
{'wdot', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('ft/s^2'), ''}; ...
    } ...
  } ...
  { ... 
    'Lin_States_bus_T', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'u', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('ft/s'), ''}; ...
{'v', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('ft/s'), ''}; ...
{'w', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('ft/s'), ''}; ...
{'p', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('rad/s'), ''}; ...
{'q', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('rad/s'), ''}; ...
{'r', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('rad/s'), ''}; ...
{'phi', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('rad'), ''}; ...
{'theta', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('rad'), ''}; ...
{'psi', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('rad'), ''}; ...
    } ...
  } ...
  { ... 
    'CMD_States_bus_T', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'theta_CMD', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('rad'), ''}; ...
    } ...
  } ...

}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
